import {Chess,DEFAULT_POSITION} from 'chess.js';
import type {Study,Color} from '../chess/types';
import {identifyOpening} from '../openings/lookup';
import {labels,performance,isError,type Label,type MoveAssessment} from './policy';
export type Phase='opening'|'middlegame'|'endgame';
interface PhaseReport{reached:boolean;total:number;analyzed:number;accuracy:number|null;errors:number;highlight:string|null}
interface PlayerReport{accuracy:number|null;performance:number|null;decisions:number;analyzed:number;total:number;counts:Record<Label,number>;phases:Record<Phase,PhaseReport>}
export function buildReport(s:Study,assessments:Record<string,MoveAssessment>):Record<Color,PlayerReport>{const make=():PlayerReport=>({accuracy:null,performance:null,decisions:0,analyzed:0,total:0,counts:Object.fromEntries(labels.map(l=>[l,0])) as Record<Label,number>,phases:Object.fromEntries(['opening','middlegame','endgame'].map(p=>[p,{reached:false,total:0,analyzed:0,accuracy:null,errors:0,highlight:null}])) as Record<Phase,PhaseReport>});const report={w:make(),b:make()};const samples:{[C in Color]:MoveAssessment[]}={w:[],b:[]};const phaseSamples:Record<string,number[]>={};let phase:Phase=s.rootFen===DEFAULT_POSITION||identifyOpening(s,s.rootId)?'opening':'middlegame';let lastBook=0;
 for(const [index,id] of s.mainline.entries()){const n=s.nodes[id],c=new Chess(n.fen),mover=new Chess(s.nodes[n.parentId!].fen).turn();if(identifyOpening(s,id)?.exact)lastBook=index+1;const pieces=c.board().flat().filter(p=>p!==null),values:Record<string,number>={n:3,b:3,r:5,q:9,p:0,k:0};const material=pieces.reduce((t,p)=>t+values[p!.type],0);const queens=pieces.filter(p=>p?.type==='q').length;const undeveloped=(color:Color)=>pieces.filter(p=>p?.color===color&&['n','b'].includes(p.type)&&p.square[1]===(color==='w'?'1':'8')).length;const developed=undeveloped('w')<=1&&undeveloped('b')<=1&&n.fen.split(' ')[2]==='-';if(material<=13||(!queens&&material<=20))phase='endgame';else if(phase==='opening'&&((index+1>=8&&developed)||(index+1>=12&&index+1>=lastBook+2)||index+1>=24))phase='middlegame';const p=report[mover],part=p.phases[phase];p.total++;part.total++;part.reached=true;const a=assessments[id];if(!a)continue;p.analyzed++;part.analyzed++;p.counts[a.primary]++;if(!a.forced){samples[mover].push(a);(phaseSamples[mover+phase]??=[]).push(a.moveAccuracy);}if(isError(a.primary))part.errors++;if(!part.highlight||a.moveAccuracy>(assessments[part.highlight]?.moveAccuracy||0))part.highlight=id;}
 for(const color of ['w','b'] as Color[]){const p=report[color],all=samples[color];p.accuracy=all.length?all.reduce((n,a)=>n+a.moveAccuracy,0)/all.length:null;const meaningful=all.filter(a=>a.meaningful);p.decisions=meaningful.length;p.performance=performance(meaningful.map(a=>({accuracy:a.moveAccuracy,gap:a.criticalGap})));for(const phase of ['opening','middlegame','endgame'] as Phase[]){const list=phaseSamples[color+phase]||[];p.phases[phase].accuracy=list.length?list.reduce((a,b)=>a+b,0)/list.length:null;}}return report;}
